package com.jalasoft.sfdc.ui.pages.account;

/**
 * @author Franz Silva
 * AccountInputs.
 */
public enum AccountEnum {
    ACCOUNT_NAME,
    PARENT_ACCOUNT,
    ACCOUNT_NUMBER,
    ACCOUNT_SITE,
    TYPE,
    INDUSTRY,
    ANNUAL_REVENUE,
    RATING,
    PHONE,
    FAX,
    WEBSITE,
    TICKER_SYMBOL,
    OWNERSHIP,
    EMPLOYEES,
    SIC_CODE,
    BILLING_STREET,
    BILLING_POSTAL,
    BILLING_CITY,
    BILLING_STATE,
    BILLING_COUNTRY,
    SHIPPING_STREET,
    SHIPPING_ZIPCODE,
    SHIPPING_CITY,
    SHIPPING_STATE,
    SHIPPING_COUNTRY,
    CUSTOMER_PRIORITY,
    SLA_EXPIRATION_DATE,
    NUMBER_OF_LOCATIONS,
    ACTIVE,
    SLA,
    SLA_SERIAL_NUMBER,
    UPSELL_OPPORTUNITY,
    DESCRIPTION

}
